import MetadataCard from './MetadataCard';
import KnowledgeBaseSection from './KnowledgeBaseSection';
import TeachingPlanTimeline from './TeachingPlanTimeline';
import LearningGapsSection from './LearningGapsSection';
import PeriodContentAccordion from './PeriodContentAccordion';
import { HiOutlineArrowUpTray } from 'react-icons/hi2';
import { HiOutlineAcademicCap } from 'react-icons/hi2';

export default function Dashboard({ data, onReset }) {
  return (
    <div className="min-h-screen px-4 py-10">
      <div className="max-w-5xl mx-auto">
        {/* Navbar strip */}
        <div className="flex items-center justify-between mb-10 pb-6 border-b border-white/5">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-xl bg-violet-600/20 border border-violet-500/30">
              <HiOutlineAcademicCap className="w-6 h-6 text-violet-400" />
            </div>
            <div>
              <h1 className="text-xl font-black gradient-text">Teacher AI</h1>
              <p className="text-xs text-slate-500">Knowledge Package Generated</p>
            </div>
          </div>
          <button
            onClick={onReset}
            className="flex items-center gap-2 px-4 py-2.5 rounded-xl border border-white/10 text-slate-400 hover:text-slate-200 hover:border-violet-500/30 hover:bg-violet-500/5 transition-all duration-200 text-sm font-medium"
          >
            <HiOutlineArrowUpTray className="w-4 h-4" />
            New Upload
          </button>
        </div>

        {/* Sections */}
        <div className="space-y-8">
          <MetadataCard metadata={data.metadata} />
          <KnowledgeBaseSection knowledgeBase={data.knowledge_base} />
          <TeachingPlanTimeline teachingPlan={data.teaching_plan} />
          <LearningGapsSection learningGaps={data.learning_gaps} />
          <PeriodContentAccordion periodContents={data.period_contents} />
        </div>

        {/* Footer */}
        <div className="mt-16 pt-6 border-t border-white/5 text-center">
          <p className="text-slate-600 text-sm">Generated by Teacher AI · Powered by LangGraph & GPT-4</p>
        </div>
      </div>
    </div>
  );
}
